### PR TITLE
changed the background color of accordion button and added a comment …

### PR DESCRIPTION
**Pull request by ujjwal1801**
It is quite difficult to keep a track of where the students have left a comment in the feedback since most of the time the students don't leave any. So I changed the background color of the accordion to a light blue color if there is a comment available from the student in that particular entry and added a comment at the end of the line in italics as well. Feel free to suggest any changes to the design. I am new to React and would love a comment from you if I followed the proper syntax and protocol for the changes.

### CODE REVIEW

**Comment by iShubhamPrakash** [comment]
Hey, @ujjwal1801  I have already added a similar feature locally and I will be pushing new changes soon. Because of this, I won't be able to merge your changes to the main branch. Thanks for contributing to the project :)

**Comment by sharynneazhar** [comment]
>  I have already added a similar feature locally and I will be pushing new changes soon. Because of this, I won't be able to merge your changes to the main branch. Thanks for contributing to the project :)

Hi @iShubhamPrakash, I was wondering if the new changes were pushed? It would help a ton if we are able to easily see which parts have comments 🙂

**Comment by iShubhamPrakash** [comment]
Hey, @sharynneazhar I apologise for not being active on this project. I'll look into this. Thanks

**Comment by iShubhamPrakash** [comment]
@sharynneazhar I just pushed a commit that will allow us to see if an item has a comment without even opening the accordion-

Screenshot 2022-07-10 at 12 33 51 PM

On expanding the accordian:

Screenshot 2022-07-10 at 12 35 21 PM

**Pull request closed without merging**
